In [1]:
import numpy as np
notre_tableau=np.array ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


numpy.ndarray

In [4]:
mon_array_bidimensionnel =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(mon_array_bidimensionnel [0] [2])
print(mon_array_bidimensionnel [0,2])
print(mon_array_bidimensionnel [0,:])
print(mon_array_bidimensionnel [:,0])

3
3
[1 2 3]
[1 4 7]


In [6]:
mon_array_bidimensionnel [0,0]='texte'

ValueError: invalid literal for int() with base 10: 'texte'

In [7]:
mon_array_bidimensionnel.dtype

dtype('int64')

In [9]:
mon_array_bidimensionnel =np.array([[1.5,2,3],[4,5.2,6],[7,8,9.1]], dtype =float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]


dtype('float64')

In [10]:
mon_array_zeros=np.zeros((4,6))
print(mon_array_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
mon_array_ones=np.ones((4,6), dtype=int)
print(mon_array_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [23]:
mon_array_random=np.random.random((4,2))
print(mon_array_random)

[[0.50918418 0.81765288]
 [0.48773089 0.71701885]
 [0.98814808 0.90869589]
 [0.3811791  0.48988772]]


In [2]:
import numpy as np
iris=np.genfromtxt('../Téléchargements/support de cours/iris.csv', delimiter =';', skip_header=True, encoding="latin-1")
print(iris)
print(iris.dtype)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

In [27]:
np.savetxt('../Téléchargements/support de cours/dico_donnees_auto_entrepreneur.xlsx', iris, delimiter =';')
print(iris.dtype)

float64


In [3]:
iris[2,1]

3.2

In [5]:
iris[2,1]=4
iris[iris>2].shape

(472,)

In [6]:
iris>2 #pour chaque cellule renvoie un booléen qui test si la valeur >2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [7]:
iris[iris [:,0]>2] #sélectionner toutes les lignes dont la première colonne >2
iris[iris [:,0]==3] #sélectionner toutes les lignes dont la première colonne =3
iris_bis=iris[iris [:,0]==3] #affecter une vue pour filtrer
iris_bis[:,4]

array([], dtype=float64)

In [8]:
notre_tableau=np.array ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
indices=np.array([[4,10,5]])
print(notre_tableau[indices])

[[ 5 11  6]]


In [9]:
A=notre_tableau[indices]
print(A[0,2])

6


In [13]:
notre_tableau[:3]
notre_tableau[10:]
notre_tableau[1:3]
notre_tableau[::3]

array([ 1,  4,  7, 10, 13, 16, 19])

In [14]:
iris[:2,:4] #sélectionner 2 premièrs lignes, 4 premières colonnes
iris[0,:] #sélectionner toutes les colonnes de la apremière ligne
iris[-1,:] #sélectionner la dernière ligne

array([5.9, 3. , 5.1, 1.8, 3. ])

In [15]:
sous_tableau=notre_tableau[:5]
sous_tableau[0] = 10 #modifier également notre_tableau (même espace mémoire)
sous_tableau=notre_tableau[:5].copy() 

In [16]:
mon_tableau =np.array([[1,2,3],[4,5,6],[7,8,9]])
np.add(mon_tableau, 10)
np.multiply(mon_tableau, 20)

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180]])

In [18]:
mon_tableau_2=np.array([10,20,30])
np.subtract(mon_tableau, mon_tableau_2)
mon_tableau_3=np.array([[1,2,3], [4,5,6], [7,8,9]])
np.multiply(mon_tableau, mon_tableau_3)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [19]:
np.sum(iris)
np.sum(iris, axis=0) #somme par colonne
np.sum(iris, axis=1) #somme par ligne
np.mean(iris, axis=0)
np.std(iris, axis=0)

array([0.82530129, 0.4409908 , 1.75940407, 0.75969263, 0.81649658])